### ISSUE TITLE
How to get OrgId and OrgName from Context?

### ISSUE THREAD

**Issue by janaki-devi** [daryllabar/XrmUnitTest#83]
Hi Daryl,

We have newly started implementing unit testing for CRM plugins and interested in your framework. Using your framework ,we are trying to get orgId and OrgName from Context. We have tried different thing to get OrgId and OrgName but they are always null . Please refer the image. Could you please help us on how to get OrgId and OrgName from Context.

![image](https://user-images.githubusercontent.com/41798799/67801159-99719500-fa56-11e9-90ce-c6106c54aef5.png)

**below is the code** 
![image](https://user-images.githubusercontent.com/41798799/67801209-b7d79080-fa56-11e9-9ebe-82919e9c2098.png)

**Comment by daryllabar** [comment]
These are empty because they haven't been set in the FakeExecutionContext.  You could create your own version of the PluginExecutionContextBuilder that sets the values of this in the Protected Context Property, or we can add it to the OOB PluginExeuctionContextBuilder as WithOrgId and With OrganizationName.  The first option you can do now, the second option you can either submit a PR, or wait for me to implement.

**Comment by janaki-devi** [comment]
For now, we will create our own version but we will be happy if you implement WithOrgId and WithOrgName .

**Comment by janaki-devi** [comment]
Do you have ETA for WithOrgId and WithOrganizationName? If it's less time , we would like to wait if not we will go with our own version of PluginExecutionContextBuilder.

**Comment by daryllabar** [comment]
Done.  v.22

**Comment by daryllabar** [comment]
Did that work for you @janaki-devi ?

**Comment by janaki-devi** [comment]
Yes, It worked for us. 
Thank you for exposing those methods.
